#include "tapdance.h"

qk_tap_dance_action_t tap_dance_actions[] = {
    [TD_POPC] = ACTION_TAP_DANCE_DOUBLE(KC_LEFT_PAREN, KC_RIGHT_PAREN),
    [TD_LBRB] = ACTION_TAP_DANCE_DOUBLE(KC_LEFT_BRACKET, KC_RIGHT_BRACKET),
    [TD_LCRC] = ACTION_TAP_DANCE_DOUBLE(KC_LEFT_CURLY_BRACE, KC_RIGHT_CURLY_BRACE),
    [TD_LARF] = ACTION_TAP_DANCE_DOUBLE(KC_LALT, KC_REFA),
    [TD_LSFT] = ACTION_TAP_DANCE_DOUBLE(KC_LSFT, KC_GOTO),
};
